### ISSUE TITLE
Needed silkscreen markings on PCBs

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZeroPhone-PCBs#52]
Front board:
- [x] Display SMD jumper pad connector pinout (#50)
- [x] Microphone polarity markings
- [x] SMD jumper pad configuration for the Heltek.cn display (likely to be the one used in production&kit versions) (#50)
- [x] Polarized capacitor polarity markings (given that most caps are tantalums, show a rectangle with a line corresponding to the line on capacitors, not just + sign) (#11)
- [x] ATMega programming header pinout (+warning about inserting the other way) (#46)
- [x] UART, VSYS and 4-pin keypad header pin names
- [x] Names for jumpers that can be cut/shorted (audio mod board overrides, ATMega GPIO mapping to 6-pin header, IR_RX/IR_TX)
- [x] R and C markings for 10K and 100nF, more detailed markings for elements with different values (put disambiguation somewhere)
- [x] For GSM filtering capacitor groups, add either "10pF" or "33pF" markings, depending on which are supposed to go where
- [x] More clear Pin 1 marking for ATMega

Back board:
- [x] Directions on soldering order: charging board first, then GSM modem, then 5V DC-DC, then USB port, then the USB testpoint wires and then the Pi Zero
- [x] Polarized capacitor polarity markings
- [x] Names for jumpers that can be cut/shorted (IR_RX/IR_TX, GSM power)
- [x] "Pull apart here" markings to see how to pull front board and back board apart
- [x] Expansion header pinout (possibly, better accomplished by stickers, for most headers)
- [x] "Hold to power" marking for FET override button
- [x] R and C markings for 10K and 100nF, more detailed markings for elements with different values
- [x] For GSM filtering capacitor groups, add either "10pF" or "33pF" markings, depending on which are supposed to go where
- [x] More clear Pin 1 marking for MCP23017

Keypad board:
- [x] Keypad row and column pin markings (for easier debugging)
- [x] Tips on soldering the keys

18650 holder board:
- [x] Version information
- [x] Battery polarity
- [x] First use instructions
- [x] 18650 battery handling warnings

**Comment by CRImier** [comment]
Done, should be on the Delta revision boards.
